package ssm;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author McKilla Gorilla & _____________
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,    
    // APPLICATION TOOLTIPS FOR BUTTONS
      TOOLTIP_NEW_EPORTFOLIO,
   TOOLTIP_LOAD_EPORTFOLIO,
TOOLTIP_SAVE_EPORTFOLIO,
TOOLTIP_SAVE_AS_EPORTFOLIO,
TOOLTIP_VIEW_EPORTFOLIO,

TOOLTIP_ADD_PAGE,
TOOLTIP_REMOVE_PAGE,
TOOLTIP_SITE_VIEWER,
TOOLTIP_WORKSPACE_MODE,     

TOOLTIP_SELECT_BANNER,
TOOLTIP_ADD_IMAGE,
TOOLTIP_ADD_VIDEO,
TOOLTIP_ADD_TEXT,
TOOLTIP_ADD_HYPERLINKER,
TOOLTIP_ADD_SLIDE_SHOW,
 TOOLTIP_ADD_LIST,
 TOOLTIP_EDIT_HEADER,
TOOLTIP_DELETE_COMPONENT, 
TOOLTIP_SELECT_COMPONENT,
TOOLTIP_VIEW_PAGE,
    TOOLTIP_NEW_SLIDE_SHOW,
     TOOLTIP_LOAD_SLIDE_SHOW,    
    TOOLTIP_SAVE_SLIDE_SHOW,     
    TOOLTIP_VIEW_SLIDE_SHOW,   
    TOOLTIP_EXIT,   
    TOOLTIP_ADD_SLIDE,   
    TOOLTIP_REMOVE_SLIDE,    
    TOOLTIP_MOVE_UP,
    TOOLTIP_MOVE_DOWN,
    TOOLTIP_PREVIOUS_SLIDE,
    TOOLTIP_NEXT_SLIDE,   
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_SLIDE_SHOW_TITLE,
   DEFAULT_PAGETITLE,
   DEFAULT_STUDENTNAME,
      // UI LABELS
    LABEL_CAPTION,  
    LABEL_PAGETITLE,
    LABEL_STUDENTNAME,
    LABEL_TITLE,
  IMAGE_DOSE_NOT_EXISTS,
  ERROR_DATA_FILE,
  INVALIDE_XML_FILE,
  NOT_ABLE_TO_SAVE,  
  SLIDE_FILE_CREATED, 
  SLIDE_FILE_NOT_CREATED,  
  NOT_ABLE_TO_LOAD_SLIDE,
  NOT_ABLE_TO_OPEN,
  NOT_ABLE_TO_SAVE_BEFORE_EXIT,
  YES_STRING,
  NO_STRING,
  CANCEL_STRING,
  NEXT_BUTTON,
  PREVIOUS_BUTTON,
  SAVE_CONFIRMATION,
WANT_TO_SAVE,
CHOOSE_SAVE,
FILE_NOT_SAVED,
PROMPT_MESSAGE,
NOT_A_IMAGE,
NOT_A_IMAGE_NOTICE,

  
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_DATA_FILE_LOADING,
    ERROR_PROPERTIES_FILE_LOADING
}
